### ISSUE TITLE
Comparison with other dataset Distillation method on LLM instruction tuning 

### ISSUE THREAD

**Issue by yfpeng1234** [magic-research/Dataset_Quantization#10]
Dear author,
Thanks for your interesting work and implementation.
I noticed that you compare DQ with other representative DD method like DM when compress image dataset.
Then I'm wondering if there is any comparison with these DD method when compress llm instruction tuning dataset?
I know that DD for llm instruction tuning dataset may consume too much GPU memory and training cost because of the model size.

Best regard

**Comment by vimar-gu** [comment]
Thanks for the interest. 
Yes the primary reason is the incompatibility of current DD methods on instruction tuning datasets. As in this work our main focus was on DQ, we didn't design new DD methods suitable for text data. But it would also be interesting to see some advances on it~

**Comment by yfpeng1234** [comment]
Thanks for your prompt reply, actually I'm quite interested in it.

Best regards

**Comment by vimar-gu** [comment]
The paper "[DiLM: Distilling Dataset into Language Model for Text-level Dataset Distillation](https://arxiv.org/abs/2404.00264)" can be a potential reference for it :)

**Comment by yfpeng1234** [comment]
Thanks so much for reminding me!
I also noted this paper.
