### ISSUE TITLE
What does “quantization” specifically mean in the paper?

### ISSUE THREAD

**Issue by haiduo** [magic-research/Dataset_Quantization#14]
Thank you for your excellent work. I have a question. Does the "quantization" of the paper refer to the second stage of "uniform sampling from generated bins" or the final "patch drop and patch restore"?  Because I can easily confuse it with model quantization. :(

**Comment by vimar-gu** [comment]
Thanks for your question. The quantization indeed is related to the model quantization. We wanted to use another word to show the difference from dataset distillation. Model quantization aims to reduce the required storage space while maintain the original performance. It is similar to our target. Additionally, we conduct the compression process in the level of pixels. Therefore, we used the word quantization for our method.

**Comment by haiduo** [comment]
Thanks for your prompt response.
