### ISSUE TITLE
When to release ImageNet selected indices

### ISSUE THREAD

**Issue by Zhou2019** [magic-research/Dataset_Quantization#15]
Will ImageNet selected indices be released? If not, how long will it take to extract it on 3090?

Thanks very much.

**Comment by vimar-gu** [comment]
I'm sorry we haven't arranged sufficient resources to reproduce the validation results. But if only for the indices selection process, the resource consumption is manageable. If I remember it correctly, it is supposed to be several hours.

**Comment by Zhou2019** [comment]
Thanks for your reply

**Comment by haiduo** [comment]
> Will ImageNet selected indices be released? If not, how long will it take to extract it on 3090?
> 
> Thanks very much.

I can provide a reference that it took me about 24-36 hours to process the bins of ImageNet-1K full samples (default 10 bins) on a single V100.
