### ISSUE TITLE
training on Imagenet

### ISSUE THREAD

**Issue by Liulei-nwpu** [magic-research/Dataset_Quantization#7]
Dear maintainers, i have found your paper really interesting and would like to replicate the results with different dataset, but i face following problem:

i have pretrained it, and when i use  `timm` for evaluating the quantized ImageNet data and run the code:

```bash
sh distributed_train.sh 9 [TRAIN_ROOT] [EVAL_ROOT] --select-indices [INDICES1] [INDICES2] --output [OUTPUT_DIR] --model resnet50 --sched cosine --epochs 260 --lr 0.6 --reprob 0.6 --remode pixel --batch-size 128 --amp --aug-splits 3 -aa rand-m9-mstd0.5-inc1 --resplit --split-bn --jsd --dist-bn reduce
```

it always reminds me that :  train.py: error: unrecognized arguments: --select-indices select_indices_SOP_0.125.npy -aa v0

do you know what the matter is ? Thank for your reply.

**Comment by vimar-gu** [comment]
I’m really sorry that the argument is supposed to be select_indices instead of select-indices. You can apply the modification and see if it fixes the problem. 

Thanks so much for the interest in our work!

**Comment by Liulei-nwpu** [comment]
Thanks for your response! And i also have another problem: i first set fraction to 0.8, but on Exp 1, it changed to 4. i don't know why. I think once i set, it should be unchangeable. Thanks for your reply. 

2024-01-06 17:32:54 "Jianyang Gu" ***@***.***> 写道：

I’m really sorry that the argument is supposed to be select_indices instead of select-indices. You can apply the modification and see if it fixes the problem.

Thanks so much for the interest in our work!
