### ISSUE TITLE
Applicability of Dataset Quantization for Multioutput Classification in MaAD-Face Dataset

### ISSUE THREAD

**Issue by MarioAvolio** [magic-research/Dataset_Quantization#9]
Hello,

I am currently exploring the use of the MAAD-Face dataset for a multioutput classification task and am considering the application of Dataset Quantization. However, I have some concerns about the suitability and effectiveness of Dataset Quantization for this specific type of dataset.

Here is a brief overview of the MAAD-Face dataset:

- **Source**: The dataset originates from the Fraunhofer Institute for Computer Graphics Research IGD Darmstadt, Germany, and the Technical University of Darmstadt, Darmstadt, Germany.
- **Composition**: MAAD-Face is a large-scale face annotations database, consisting of over 9.1k identities and more than 3.3M face images, with various poses, ages, and illuminations.
- **Annotations**: It features annotations for 47 distinctive attributes, totaling 38.3M annotations. 
- **Public Accessibility**: The dataset is publicly available for research purposes

Given the structure and scale of the MAAD-Face dataset, I am seeking advice on the following:

1. **Compatibility**: Is Dataset Quantization compatible with a dataset like MAAD-Face, which is designed for multioutput classification tasks?
   
2. **Performance Impact**: What could be the potential impact of Dataset Quantization on the accuracy and efficiency of models trained on this dataset?

3. **Implementation Best Practices**: If Dataset Quantization is suitable, what are the recommended practices for its implementation in a multioutput classification context?

4. **Existing Studies**: Are there any studies or examples where Dataset Quantization has been applied to similar datasets?

5. **Recommended Tools and Libraries**: What tools or libraries would you recommend for implementing Dataset Quantization with the MAAD-Face dataset?

Any insights, experiences, or references you could provide would be incredibly helpful for my research. Thank you in advance for your time and assistance.

Best regards,
Mario.

**Comment by vimar-gu** [comment]
Hi Mario. Thanks so much for your interest in dataset quantization!

1. Dataset quantization definitely can be applied to MAAD-Face. DQ first involves a functioning model that is trained on the target dataset. For this specific case, you can first train a model on the multi-output  classification task. Then DQ selects effective samples in the embedding space based on the relationship among samples of each class. That is to say, the sample selection process is not only applicable for standard classification task, but can be applied to any tasks where there is a model extracting embeddings. 
2. Generally DQ wouldn't affect the accuracy with a proper compression ratio setting. And with reduced sample number, the training efficiency can be largely improved. 
3. Based on 1, the only modification would be a different model structure. The remaining steps are the same. 
4. Unfortunately we haven't applied DQ directly to other tasks except for standard classification. 
5. Basically you still can use this repo for building the data selection pipeline by changing the model structures and data loading functions inside. 

Thanks again for your interest. If there are any further questions, please don't hesitate to contact me.
